# Generated by Django 5.0.6 on 2026-07-10 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_language', models.CharField(max_length=10)),
                ('listener_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('active', 'Active'), ('qa_mode', 'Q&A'), ('ended', 'Ended')], default='not_started', max_length=20)),
                ('approved_listener_uuid', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('interpreter_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('is_source', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='kabin_sessions.session')),
            ],
            options={
                'ordering': ['-is_source', 'language'],
                'indexes': [models.Index(fields=['session'], name='kabin_sessi_session_eb8000_idx')],
            },
        ),
    ]
