# Generated by Django 5.0.6 on 2026-07-10 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabin_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListenerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listener_uuid', models.UUIDField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kabin_sessions.channel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listener_sessions', to='kabin_sessions.session')),
            ],
        ),
        migrations.AddConstraint(
            model_name='listenersession',
            constraint=models.UniqueConstraint(fields=('session', 'listener_uuid'), name='unique_listener_per_session'),
        ),
    ]
