# Generated by Django 5.0.6 on 2026-07-12 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabin_sessions', '0002_listenersession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelInterpreter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interpreter_claim', to='kabin_sessions.channel')),
                ('interpreter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_claims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
