# Generated by Django 5.0.6 on 2026-07-12 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabin_sessions', '0003_channelinterpreter'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaiseHandEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listener_uuid', models.UUIDField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_hands', to='kabin_sessions.session')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='raisehandentry',
            constraint=models.UniqueConstraint(fields=('session', 'listener_uuid'), name='unique_raised_hand_per_session'),
        ),
    ]
