# Generated by Django 5.0.6 on 2026-07-12 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabin_sessions', '0004_raisehandentry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_kind', models.CharField(choices=[('guide', 'Guide'), ('interpreter', 'Interpreter'), ('listener', 'Listener')], max_length=20)),
                ('sender_listener_uuid', models.UUIDField(blank=True, null=True)),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='kabin_sessions.session')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
