# Generated by Django 5.0.6 on 2026-07-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabin_sessions', '0005_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='approved_listener_uuid',
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('active', 'Active'), ('ended', 'Ended')], default='not_started', max_length=20),
        ),
        migrations.DeleteModel(
            name='RaiseHandEntry',
        ),
    ]
