# Generated by Django 5.0.6 on 2026-07-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabin_sessions', '0006_remove_qa_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='interpreter_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
