# Generated by Django 5.0.6 on 2026-07-21 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabin_sessions', '0007_make_source_interpreter_code_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelinterpreter',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interpreter_claims', to='kabin_sessions.channel'),
        ),
        migrations.AddConstraint(
            model_name='channelinterpreter',
            constraint=models.UniqueConstraint(fields=('channel', 'interpreter'), name='unique_interpreter_claim_per_channel'),
        ),
    ]
