# Generated by Django 5.0.6 on 2026-07-21 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabin_sessions', '0008_multi_interpreter_per_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender_listener_uuid',
        ),
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='kabin_sessions.channel'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_kind',
            field=models.CharField(choices=[('guide', 'Guide'), ('interpreter', 'Interpreter')], max_length=20),
        ),
    ]
