# Generated by Django 5.0.6 on 2026-07-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabin_sessions', '0009_remove_message_sender_listener_uuid_message_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
